### ISSUE TITLE
Monkeyprint freezing

### ISSUE THREAD

**Issue by kakaroto** [robotsinthesun/monkeyprint#11]
I have noticed sometimes that monkeyprint will be completely frozen. I haven't yet figured out what causes this to happen, so I can't reproduce it, but it happened to me a couple of times already.
One thing that I notice though is that every time it happens, monkeyprint will stay completely frozen no matter what I do, unless I go to the terminal and press Ctrl-C, in which case, it will not kill the process, but instead, it will unfreeze it.
When that happens, this is what I get on the terminal :

```
^CTraceback (most recent call last):
  File "/home/kakaroto/monkeyprint/monkeyprintSocketCommunication.py", line 124, in pollRasPiConnection
    self.socket.send_multipart([command, path])
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 271, in send_multipart
    self.send(msg, SNDMORE|flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 574, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5434)
  File "zmq/backend/cython/socket.pyx", line 621, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:5196)
  File "zmq/backend/cython/socket.pyx", line 181, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2035)
  File "zmq/backend/cython/checkrc.pxd", line 11, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6022)
KeyboardInterrupt
```

It looks like it becomes frozen on a socket.send for the rasberri pi connection, but I don't have any rpi here, so I'm not sure where that comes from. Should probably be trivial to fix once I looked at the code.

**Comment by robotsinthesun** [comment]
I know where this comes from. I was experimenting with socket 
connections to talk to a Raspberry Pi but forgot to remove this from the 
release branch. Seems one of the socket methods that tries to connect to 
the Pi times out...

This stuff simply should not be called if the Raspberry Pi option is not 
enabled. I'll disable it tomorrow.

**Comment by kakaroto** [comment]
Ok cool, I figured it was something like that, but hadn't had time to look at the code and created the issue so I wouldn't forget about it. I'll probably have some time later today to look at it.

**Comment by robotsinthesun** [comment]
Hi Youness,

I've disabled the socket stuff for now in the release branch. Can you 
check if the freezes still happen?

Best,
Paul

**Comment by kakaroto** [comment]
That was fast, thanks! I'll let you know if I see it freezing again.
Closing issue.
