### ISSUE TITLE
Any plans to update vtk for Ubuntu?

### ISSUE THREAD

**Issue by nafergo** [robotsinthesun/monkeyprint#24]
Have problems while installing dependencies on Ubuntu 17.04:
- E: Couldn't find any package by glob 'libvtk5.10'
- E: Package 'python-vtk' has no installation candidate

and after, while trying to run...

Traceback (most recent call last):
  File "./monkeyprint.py", line 25, in <module>
    import monkeyprintModelHandling
  File "/home/nafergo/monkeyprint/monkeyprintModelHandling.py", line 24, in <module>
    import vtk
ImportError: No module named vtk

**Comment by robotsinthesun** [comment]
Hi and sorry for the delay...
have you tried using the VTK version that is available in your distro? That should be libvtk6.3 if I'm correct. If it works, please give some feedback here!
