### ISSUE TITLE
Slice image size is one pixel too large when model is autoscaled to max build volume

### ISSUE THREAD

**Issue by robotsinthesun** [robotsinthesun/monkeyprint#3]
Traceback (most recent call last):
  File "/home/paul/Projects/printer/monkeyprint/monkeyprintGui.py", line 1152, in updateSlicePrint
    self.windowPrint.updateImage(sliceNumber)
  File "/home/paul/Projects/printer/monkeyprint/monkeyprintGuiHelper.py", line 946, in updateImage
    image = self.modelCollection.updateSliceImage(sliceNumber)
  File "/home/paul/Projects/printer/monkeyprint/monkeyprintModelHandling.py", line 595, in updateSliceImage
    self.sliceImage = imageHandling.imgAdd(self.sliceImage, imgList[i][0], imgList[i][1])
  File "/home/paul/Projects/printer/monkeyprint/monkeyprintImageHandling.py", line 79, in imgAdd
    img1[bounds[0]:bounds[1] , bounds[2]:bounds[3] ] = (img1[bounds[0]:bounds[1] , bounds[2]:bounds[3] ] + img2)
ValueError: operands could not be broadcast together with shapes (768,1007) (769,1007)

**Comment by robotsinthesun** [comment]
fixed
